### ISSUE TITLE
is there a good way to get session for different bind/database

### ISSUE THREAD

**Issue by skeetwu** [pallets-eco/flask-sqlalchemy#1017]
Hi,

I need to bind multiple databases, and there is a good way to do it as follow document.
https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/

but, after that, sometimes I want to run a plain-text SQL directly via Session for different databases/bind.
I ready the source code in this project, and implatment it like this.
```python
@contextmanager
def session_scope(bind='default'):
    if bind != 'default':
        s = db.create_scoped_session(options={'bind': db.get_engine(db.get_app(), bind)})
    else:
        s = db.session

    s.expire_on_commit = False
    try:
        yield s
        s.commit()
    except:
        s.rollback()
        raise
    finally:
        s.close()
```
I want to know if there is a more graceful way to get a session, if not, I suggest adding a function in class SQLAlchemy.
```python
def get_session_by_bind(self, bind=None):
    if bind:
        return self.create_scoped_session(options={'bind': self.get_engine(self.get_app(), bind)})
    else:
       return self.session
```

B&R

**Comment by davidism** [comment]
You should not need to do this, the session automatically chooses a bind based on the model's or table's bind key. Otherwise, you can call `session.execute(bind=...)` to execute with a specific bind.

**Comment by skeetwu** [comment]
> You should not need to do this, the session automatically chooses a bind based on the model's or table's bind key. Otherwise, you can call `session.execute(bind=...)` to execute with a specific bind.

OK， thx your response.
