### ISSUE TITLE
SqlAlchemy warning raised using pagination api.

### ISSUE THREAD

**Issue by brassy-endomorph** [pallets-eco/flask-sqlalchemy#1038]
The following warning is raised when using the pagination API.

```
/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py:550:
  SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
```

Possibly related to or covered by #1010 

Environment:

- Python version: 3.10
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.4.31

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. That said, we'll be adding a new way to paginate `select()` statements since the query interface is legacy in SQLAlchemy 2.0.
