### ISSUE TITLE
Serialize SqlAlchemy object to JSON.

### ISSUE THREAD

**Issue by tanveersultan53** [pallets-eco/flask-sqlalchemy#1062]
**Model.query.get(id=1) Result convert into Json/Dict.**

**Example**

```
class MyModel(db.Model):
    """
   Model Discription
    """
    __tablename__ = 'table_ name'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(256), nullable=True)
```

```
model_object = MyModel.query.get(id=1)
```
```
result = model_object.as_dict()
```
**Return a Json Object.**
```
{
"id":1,
"name":"test_name_value",
}
```

**Comment by davidism** [comment]
This is impossible to implement in a general way that would support any arbitrary use of SQLAlchemy. You are looking for a serialization library like cattrs, Marshmallow, Pydantic, etc.

**Comment by tanveersultan53** [comment]
> This is impossible to implement in a general way that would support any arbitrary use of SQLAlchemy. You are looking for a serialization library like cattrs, Marshmallow, Pydantic, etc.

@davidism its not impossible i implement locally and test it so i provide the solution of this ticket.

**Comment by davidism** [comment]
Yes, you implemented it for your specific (and probably fairly trivial) use of SQLAlchemy. I guarantee you it is not generally applicable to SQLAlchemy's capabilities.

**Comment by tanveersultan53** [comment]
i thinks you underestimate the solution. i create a PR  after reviewing the Pull Request you have to decide. 
thanks & Regards.

**Comment by tanveersultan53** [comment]
> Yes, you implemented it for your specific (and probably fairly trivial) use of SQLAlchemy. I guarantee you it is not generally applicable to SQLAlchemy's capabilities.

i thinks you underestimate the solution. i create a PR after reviewing the Pull Request you have to decide.
thanks & Regards.

**Comment by tanveersultan53** [comment]
> Yes, you implemented it for your specific (and probably fairly trivial) use of SQLAlchemy. I guarantee you it is not generally applicable to SQLAlchemy's capabilities.

can you reopen the ticket.

**Comment by ThiefMaster** [comment]
There's a 99% chance your PR won't be merged. You're of course free to open it nonetheless. There is no need to reopen this issue though.

As someone who was two flexible-but-not-very-great serialization implementations that were (somewhat) generic, and was happy to remove both from my codebase in favor of marshmallow schemas I agree with @davidism that this should not be in flask-sqlalchemy.
