### ISSUE TITLE
Add an option to disable CamelCase to snake_case conversion

### ISSUE THREAD

**Issue by Namerif** [pallets-eco/flask-sqlalchemy#1063]
I noticed that Flask-SQLAlchemy converts class names from CamelCase to snake_case, but I think users should have an option to disable this behavior, because:
1. It's unintuitive, and most new developers assume that in relations they have to specify name of class as it is written in the code
2. It doesn't make sense for the same thing to be called different ways in different contexts
3. It makes developing harder, since you need to think which name you should use depending on where and how you address a table

Right now, it can be achieved with this:
```
import flask_sqlalchemy.model
flask_sqlalchemy.model.camel_to_snake_case = lambda x: x
```
But it doesn't seem like a good solution, and it might create some problems, so I suggest adding this as app.config option (for example, "SQLALCHEMY_KEEP_TABLES_NAMES").

If there are some good reasoning of having this feature that I'm not considering, please let me know since I don't have too much experience yet and can miss something important. Also, if the contributors agree this is a useful feature, I can try to implement it myself and create a pull-request.

**Comment by davidism** [comment]
You can still specify `__tablename__ = "..."` for each model, just like you'd have to if autonaming was disabled. So I don't think there's a reason to disable it. The rest of your points mostly seem like a misunderstanding of what SQLAlchemy does and the common patterns it uses, which aren't changed by us generating names.

> It's unintuitive, and most new developers assume that in relations they have to specify name of class as it is written in the code

I think it is intuitive, it's why the feature exists in the first place. Also, you still specify names in SQLAlchemy `relationship` constructs using the class name, this doesn't change how that works.

> It doesn't make sense for the same thing to be called different ways in different contexts

Take it up with SQLAlchemy. The whole point of it is to map classes to tables, and all examples of table names use snake_case while the models use CamelCase. The fact that we autogenerate them doesn't change that.

> It makes developing harder, since you need to think which name you should use depending on where and how you address a table

It doesn't. In pretty much every case in SQLAlchemy, you use class names. For the places that do require table names, whether they're generated or not doesn't matter, you still need to know to use the table name.

**Comment by Namerif** [comment]
> You can still specify `__tablename__ = "..."` for each model, just like you'd have to if autonaming was disabled.

But autonaming is actually one of the main features I (and probably many people) are using Flask-SQLAlchemy instead of Flask + SQLAlchemy in the first place. It makes development more convenient with these things, so you don't need to remember to change __tablename__ when you change class name (it's easy if you rename class with refactor option in IDE, and not directly in models.py).
> Also, you still specify names in SQLAlchemy relationship constructs using the class name, this doesn't change how that works.

Yes, sorry, here I confused it with db.ForeignKey, where you have to use table name. But for me it makes inconsistency even more obvious, since it's string both in relationship and ForeignKey, but in first you should use class name, and in second table name.
> Take it up with SQLAlchemy.

But SQLAlchemy doesn't have autonaming and requires users to name tables themselves, so what is the point of discussing it with them? As for examples, I've read some questions on Stackoverflow, and it seems like there is no convention of how to name tables, and both cases are quite widely used (correct me if I'm wrong), so it sounds like a good idea to let people choose what they prefer.
>  For the places that do require table names, whether they're generated or not doesn't matter, you still need to know to use the table name.

Can you please clarify this point? Because for me if table is named exactly like class, you have to know only the class name, and then you can use everywhere not thinking whether table or class name is needed here.

Overall, I understand that you might not want to change it because snake_case is preferred in this project or SQLAlchemy. But I'm not asking for disabling this feature at all or even changing the default behavior. All I'm suggesting is to add an option which would be really nice for people like me who prefer CamelCase in tables names and like the autonaming feature. Therefore I would appreciate if you elaborate on why you reject this idea a little more, especially if I will be able to implement this myself.

**Comment by ThiefMaster** [comment]
IMHO camelCase does not belong into a database. Take Postgres for example (probably quite a few other DBs do the same):

- by default, names are case insensitive
- only if you put them in double quotes, their case becomes relevant (and in that case they *are* case sensitive)

So I'm also against adding explicit support for this - especially considering you already have a somewhat easy way of doing it yourself if you want to.

**Comment by davidism** [comment]
The SQLAlchemy built-in way to control exactly what tablenames are generated is to override the `__tablename__` property on the model. See the SQLAlchemy docs for more information. I don't plan to add any customization beyond that.

**Comment by Namerif** [comment]
> IMHO camelCase does not belong into a database. Take Postgres for example (probably quite a few other DBs do the same):
> 
>     * by default, names are case insensitive
> 
>     * only if you put them in double quotes, their case becomes relevant (and in that case they _are_ case sensitive)

Unfortunately, I'm not familiar with Postgres, but based on your points, it sounds like it can store the case, it just doesn't matter when you address the table. So if my assumption is correct, CamelCase (or rather PascalCase) can be used here without problems, given that you're using it consistently. And as a counter-example, I can give T-SQL, which according to this [document](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Name%20Convention%20and%20T-SQL%20Programming%20Style.md), uses PascalCase in tables names as convention and is even more popular than Postgres according to this [statistics](https://www.statista.com/statistics/1131568/worldwide-popularity-ranking-relational-database-management-systems/).

**Comment by Namerif** [comment]
But I'll probably finish the discussion at this point, as my voice doesn't weigh much compared to the two contributors :)

Sorry if my comments sounded a bit assertive, just wanted to improve the library I'm using and thought it was a good idea. But thanks anyway for developing this project and investing your time into considering this suggestion, even though it was rejected!
