### ISSUE TITLE
SQLAlchemy mapper_configured event not invoked

### ISSUE THREAD

**Issue by kvesteri** [pallets-eco/flask-sqlalchemy#108]
The SQLAlchemy event mapper_configured is not invoked when using Flask-SQLAlchemy based models.

http://docs.sqlalchemy.org/en/rel_0_7/orm/events.html#sqlalchemy.orm.events.MapperEvents.mapper_configured

``` python
from sqlalchemy import event
from sqlalchemy.orm.mapper import Mapper
# flask configuration here

class MyModel(db.Model):
    __tablename__ = 'my_model'
    id = db.Column(db.Integer, primary_key=True)

def my_listener(mapper, class_):
    print "Hi!"


# attach to all mappers
event.listen(Mapper, 'mapper_configured', my_listener)

MyModel()  # should print 'Hi!', does not print anything
```

**Comment by Alain1405** [comment]
@kvesteri I'm trying to use your sqlalchemy-defaults with Flask-SqlAlchemy + Flask-migrate but indeed it seems like the Mapper events are not catched. 
Were you able to solve?

**Comment by kvesteri** [comment]
@Alain1405 , on some of my projects I've ended up calling ``sa.orm.configure_mappers()`` in order to force invoke mapper events.
