### ISSUE TITLE
2.4 change notes missing deprecated config

### ISSUE THREAD

**Issue by lehmat** [pallets-eco/flask-sqlalchemy#1128]
I ran into issues with MySQL lost connection after releasing to production. I looked more closely and I found out that there are some changes documented in docs but not in changelog:

> Changed in version 3.0: Removed SQLALCHEMY_NATIVE_UNICODE, SQLALCHEMY_POOL_SIZE, SQLALCHEMY_POOL_TIMEOUT, SQLALCHEMY_POOL_RECYCLE, and SQLALCHEMY_MAX_OVERFLOW

The request is to add mention about depreciated configuration parameters to changelog

**Comment by davidism** [comment]
19e2fdf9a60aa98f296daebd1473dfa712db28f2
