### ISSUE TITLE
Incompatibility between Flask-SQLAlchemy >= 3.0.0 and PySerde

### ISSUE THREAD

**Issue by barsa-net** [pallets-eco/flask-sqlalchemy#1132]
It seems there is an incompatibility between Flask-SQLAlchemy >= 3.0.0 and PySerde ([https://github.com/yukinarit/pyserde](https://github.com/yukinarit/pyserde)) when applying ORM to a dataclass.

Example:
```
from dataclasses import dataclass

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from serde import serde

db = SQLAlchemy()
app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"
db.init_app(app)


@serde
@dataclass
class User(db.Model):
    Id: int = db.Column("id", db.Integer, primary_key=True)
    Name: str = db.Column("name", db.String)


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()
```
Exits with an error:
```
serde.compat.SerdeError: Failed to resolve type hints for User:
NameError: name 'SQLAlchemy' is not defined

If you are using forward references make sure you are calling deserialize & serialize after all classes are globally visible.
```
This is caused by the `db.Model` typing of `__fsa__`
https://github.com/pallets-eco/flask-sqlalchemy/blob/d0568f54deb6310a4059201cc3c8d5ee95ad1ad9/src/flask_sqlalchemy/model.py#L36-L40

The same code works fine with Flask-SQLAlchemy 2.5.1

Environment:
- Python version: 3.9.15
- Flask-SQLAlchemy version: 3.0.1
- SQLAlchemy version: 1.4.42

**Comment by davidism** [comment]
I'm not familiar with pyserde, but this sounds like a bug with that library. For example, they probably shouldn't be serializing the `__fsa__` object to begin with, it's a private variable.

**Comment by barsa-net** [comment]
By the way, if I understand correctly you consider this a "not a bug, wont fix", if that's the case i'll use a different `model_class` as a workaround.

**Comment by davidism** [comment]
It's "can't fix" not "won't fix". You can only call `get_type_hints` if all names are in scope. But a standard pattern in typing is to keep circular references out of scope using `if TYPE_CHECKING`. You need to take this up with pyserde or Python.
