### ISSUE TITLE
Per Page Argument Limits

### ISSUE THREAD

**Issue by ibraheemalayan** [pallets-eco/flask-sqlalchemy#1143]
A client called a pagination endpoint and passed a very big value in the `per_page` parameter which broke the system, it was bigger than the range of big integer in PostgreSQL leading to the following error.

```
(psycopg2.errors.NumericValueOutOfRange) bigint out of range

[SQL: SELECT ***********************
 LIMIT %(param_1)s OFFSET %(param_2)s]
[parameters: {'param_1': 2000000000000000000000000000, ********
(Background on this error at: https://sqlalche.me/e/14/9h9h)
```

Are there any intentions to add a check for those limits in the library itself, or should it be implemented in the app level ? ( in every endpoint that has a pagination query )

Environment:

- Python version: 3.9.15
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.4.42

**Comment by davidism** [comment]
This is already implemented, check the documentation.
