### ISSUE TITLE
Documentation bug on queries.rst

### ISSUE THREAD

**Issue by richard-to** [pallets-eco/flask-sqlalchemy#1152]
On this page https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/queries/#select, the information for querying one object is slightly incorrect.

```
user = db.session.execute(db.select(User).filter_by(username=username)).one()
```

This yields something like:

```
(<User 1>,)
```

I believe this is because we are working with the ORM models, so we need to use ScalarResult instead of Result. See https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.ScalarResult

So I think the example should read:

```
user = db.session.execute(db.select(User).filter_by(username=username)).scalars().one()
```

This will yield the model with out the tuple.

```
<User 1>
```

Environment:

- Python version: 3.11.0
- Flask-SQLAlchemy version: 3.0.2
- SQLAlchemy version: 1.4.44

------

I'm happy to update the documentation. I was considering sending a pull request, but it's late, so ended up filing a bug instead.

**Comment by davidism** [comment]
b48c2da
