### ISSUE TITLE
SQLAlchemy 2.0 Related LegacyAPIWarning

### ISSUE THREAD

**Issue by mokadevcloud** [pallets-eco/flask-sqlalchemy#1156]
Environment:

- Python version: 3.8.10
- Flask-SQLAlchemy version: 3.0.2
- SQLAlchemy version: 1.4.46

Hi, I'm getting a big fat warning for a simple  `event = Event.query.get(id)`:

```
/home/moka-repo/app/daos/event.py:54: LegacyAPIWarning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```
I read up on the SQAlchemy 2.0 site and a few issues here, but can't figure out how to make the code compatible with the upcoming release. Any pointers? Thanks

**Comment by davidism** [comment]
You need to fix your code, it's not something within Flask-SQLAlchemy. It's likely `query`, that interface is considered legacy in SQLAlchemy 2.0. Both SQLAlchemy and Flask-SQLAlchemy docs discuss this already.

Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.
