### ISSUE TITLE
I can't connect api's db to pandas anymore.

### ISSUE THREAD

**Issue by Chokhonelidze** [pallets-eco/flask-sqlalchemy#1164]
Hi,
I can not connect api 's db to pandas anymore 
I used to use:
df = pd.read_sql_table('songs',db.get_engine(),index_col='id')
it was working for some time but after 1 install it started to throw error:
OptionEngine' object has no attribute 'execute'
I checked my versions and it shows that I had 3.0.2 before and updated to 3.0.3
I tried to install 3.0.2 again and having this error.
please let me know what replacement can I use to pass the engine to pandas for 3.0.2 or 3.0.3.
Environment:

- Python version:3.9
- Flask-SQLAlchemy version:3.0.2
- SQLAlchemy version: not using

**Comment by davidism** [comment]
The error you're showing (please remember to include full tracebacks when reporting issues) indicates that this is an issue with SQLAlchemy, not Flask-SQLAlchemy. Search the SQLAlchemy and Pandas issues trackers to look for similar issues, or open a new one there if none exist.

**Comment by Chokhonelidze** [comment]
Hi Davidism,
thank you for your response but I don't have any SQLAlchemy installed:
flask = "*"
ariadne = "*"
flask-cors = "*"
psycopg2-binary = "*"
pandas = "*"
surprise = "*"
numpy = "*"
passlib = "*"
pytube = "*"
flask-sqlalchemy = "===3.0.2"
how it is the issue with SQLAlchemy when I am using just flask-sqlalchemy ?

**Comment by davidism** [comment]
You do, in fact, have SQLAlchemy. Please follow what I wrote in my previous comment, rather than continuing here.

**Comment by Chokhonelidze** [comment]
@davidism oh that fixed my problem thank you.
