### ISSUE TITLE
Session:get_bind() does no longer support joining an external session

### ISSUE THREAD

**Issue by nblock** [pallets-eco/flask-sqlalchemy#1167]
I'm trying to implement the pattern described in [Joining a Session into an External Transaction (such as for test suites)](https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#joining-a-session-into-an-external-transaction-such-as-for-test-suites) with Flask-SQLAlchemy 3.0 and Pytest. This used to work in Flask-SQLAlchemy 2.x and is [documented here](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/api/#flask_sqlalchemy.session.Session.get_bind).

Here is a minimal example (`app.py`):

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///example.sqlite"
db = SQLAlchemy(app)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)


@app.get("/<id>")
def greet(id):
    user = db.get_or_404(User, id)
    return f"hi, {user.username}"
```

Test code (`tests.py`):

```python
import pytest
from flask import url_for
from flask_sqlalchemy.session import Session
from sqlalchemy.orm import scoped_session, sessionmaker

from app import User
from app import app as app_
from app import db as db_


class MySession(Session):
    def get_bind(self, *args, **kwargs):
        if self.bind:
            return self.bind
        return super().get_bind(*args, **kwargs)


@pytest.fixture(scope="session")
def app():
    yield app_


@pytest.fixture(scope="session")
def db(app):
    with app.app_context():
        db_.create_all()
        yield db_
        db_.drop_all()


@pytest.fixture
def session(db):
    connection = db.engine.connect()
    transaction = connection.begin()

    factory = sessionmaker(class_=Session, db=db, bind=connection)
    # factory = sessionmaker(class_=MySession, db=db, bind=connection)
    db.session = scoped_session(session_factory=factory)
    yield db.session

    db.session.close()
    transaction.rollback()
    connection.close()


def test_one(client, session):
    user = User(username="john")
    session.add(user)
    session.commit()

    response = client.get(url_for("greet", id=user.id))

    assert response.status_code == 200


def test_two(client, session):
    user = User(username="john")
    session.add(user)
    session.commit()

    response = client.get(url_for("greet", id=user.id))

    assert response.status_code == 200
```

Requirements:

```
Flask-SQLAlchemy==3.0.3
pytest-flask==1.2.0
```

Using the `Session` as provided by Flask-SQLAlchemy yields the following exception when running the test suite:

```bash
pytest tests.py
# [snipped]
    self.dialect.do_execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x7f9ccf77d2d0>, cursor = <sqlite3.Cursor object at 0x7f9ccf4bde40>, statement = 'INSERT INTO user (username) VALUES (?)', parameters = ('john',)
context = <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x7f9ccf4d9310>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
E       [SQL: INSERT INTO user (username) VALUES (?)]
E       [parameters: ('john',)]
E       (Background on this error at: https://sqlalche.me/e/14/gkpj)

../../.pyenv/versions/3.11.1/envs/example/lib/python3.11/site-packages/sqlalchemy/engine/default.py:736: IntegrityError
=========================================================================================================== short test summary info ===========================================================================================================
FAILED tests.py::test_two - sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
========================================================================================================= 1 failed, 1
passed in 0.60s ===
```

It seems that the engine is used instead of the provided `connection`, thus breaking the isolation. However, SQLAlchemy's implementation in `Session:get_bind()` seems to [handle this case](https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_2/lib/sqlalchemy/orm/session.py#L2607):

```python
        elif not self.__binds and self.bind:
            # simplest and most common case, we have a bind and no
            # per-mapper/table binds, we're done
            return self.bind
```

The sample code works with the (hackish) `MySession` class that loosely follows the implementation of SQLAlchemy. Enable it via the commented line: `factory = sessionmaker(class_=MySession, db=db, bind=connection)` to see the difference.

Environment:

- Python version: 3.11.1
- Flask-SQLAlchemy version: 3.0.3
- SQLAlchemy version: 2.0.2 or 1.4.46

**Comment by davidism** [comment]
> However, SQLAlchemy's implementation in `Session:get_bind()` seems to handle this case

We don't handle binds in the same way, so we can't add that same logic. We support looking up binds by the bind key on the model/table/metadata handling the query. If nothing else, your example only supports overriding one connection, not multiple binds.

> The sample code works with the (hackish) MySession class

That's fine, if you have a way to make the tests work the way you need, use that. Using SQLAlchemy's plain `Session` is fine as well, you can even populate its `binds` argument with the appropriate connection for each model.

In general, if you want the behavior of the regular `Session`, use that. You're not required to use Flask-SQLAlchemy's `Session` class if you don't want it's behavior.

---

That said, there's probably some way to override `db.engines` to use your own mapping of connections. This probably isn't working, but the idea would be:

```python
@pytest.fixture
def db(app, monkeypatch):
    with app.app_context():
        engines = db_.engines

    cleanup = []

    for key, engine in engines.items():
        c = engine.connect()
        t = c.begin()
        monkeypatch.setattr(engines, key, c)
        cleanup.append((c, t))

    yield db_

    for c, t in cleanup:
        t.rollback()
        c.close()
```

---

Tangential to the issue you're asking about, the following code is wrong and will cause your tests to break in other ways:

```python
@pytest.fixture(scope="session")
def db(app):
    with app.app_context():
        db_.create_all()
        yield db_
        db_.drop_all()
```

You should not push an app context for the entire duration of an individual test or the entire test session. Instead, push it only during the moments you need it.

```python
    with app.app_context():
        db.create_all()

    yield db

    with app.app_context():
        db.drop_all()
```

**Comment by nblock** [comment]
Thanks a lot for the hint regarding `yield db` with regards to the app context and the implementation suggestions. I'll take a look at you suggested implementation using `db.engines`.
