### ISSUE TITLE
Document how to use same codebase for models with pure SQLAlchemy and Flask-SQLAlchemy

### ISSUE THREAD

**Issue by iTrooz** [pallets-eco/flask-sqlalchemy#1176]
I believe this issue is a recurrent one, as it has been asked a lot, for example in
https://github.com/pallets-eco/flask-sqlalchemy/issues/60
https://github.com/pallets-eco/flask-sqlalchemy/pull/61
https://github.com/pallets-eco/flask-sqlalchemy/pull/255
https://github.com/pallets-eco/flask-sqlalchemy/issues/98
https://github.com/pallets-eco/flask-sqlalchemy/pull/250
https://github.com/pallets-eco/flask-sqlalchemy/pull/629
https://github.com/pallets-eco/flask-sqlalchemy/pull/791

but I still don't see it documented officially. Personally, I had to search through all these issues to find (hackish) ways to solve it ! (And I'm still not sure what to use)

I think that being able to use Models without Flask is a very important feature, as I feel like coupling models with flask violates the Single Responsibility principle of SOLID

I plan to do a blog post to help share code examples and solutions about this issue, but I believe writing about it in the official documenting would be more helpful

**Comment by iTrooz** [comment]
> that you can simply init the Flask app and push an app context and then just use F-SA

IMO that's not a good solution because you still have a dependency on flask, for things that may be be totally unrelated.
For example, I do not want a database import script to have a dependency on Flask

A few things that comes to mind :
- What if I need to use the models in a environment where Flask is not installed ?
- What if I want to replace Flask with, say, Django, or another new framework that has support for SQLAlchemy ?
- What if flask evolves to make the "app init" much bigger, and so I use a lot of computing power for nothing/the flask app crashes because not configured right ?

**Comment by davidism** [comment]
https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/customizing/ shows how to use different models or model bases, and session classes. https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/api/#flask_sqlalchemy.SQLAlchemy shows parameters for customizing the model, model base, session, and metadata.

**Comment by iTrooz** [comment]
I'm sorry, but I don't see anything in https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/customizing/ that would help me to, for example, create models without Flask-SQLAlchemy, and then integrate them in Flask-SQLALchemy. Do you have any example please ?

**Comment by davidism** [comment]
You create a base class, then pass it as `SQLAlchemy(model=MyBaseModel)`.

**Comment by iTrooz** [comment]
I ended up with this (https://gist.github.com/iTrooz/5cba78812013de8a6608fa665698a376) which works, thanks !

But I still do not see anything like this in https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/customizing/ . There are example about the use of `model_class`, but none to actually define models

Would you accept a pull request to add one ?

**Comment by davidism** [comment]
No, I don't plan to expand that part of the documentation.
