### ISSUE TITLE
'Lost connection to MySQL server during query' on database restart

### ISSUE THREAD

**Issue by iTrooz** [pallets-eco/flask-sqlalchemy#1177]
When I restart my database (to simulate a timeout/network error/etc..), the next request my application process gets a 'Lost connection to MySQL server during query' error. Next requests process normally

Example code to reproduce:
```
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import engine as eg

# Create Flask app
app = Flask(__name__)

db_url = eg.URL.create(
            "mariadb+pymysql",
            username="",
            password="",
            host="",
            database=""
        )

# Configure Database
app.config['SQLALCHEMY_DATABASE_URI'] = db_url
db = SQLAlchemy(app)

# Create model
class Test(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    a = db.Column(db.String)
    b = db.Column(db.String)

    def __str__(self):
        return "Test(%s, %s)" % (self.a, self.b)

    def __repr__(self):
        return self.__str__()

# Create route
@app.route('/')
def hello_world():
    rows = Test.query.all()
    return "|".join(str(row) for row in rows)

if __name__ == '__main__':
    app.run(debug=True)
```

Versions:
- Python: 3.10.9
- Flask-SQLAlchemy 3.0.2
- SQLAlchemy: 2.0.5.post1
- Flask: 2.2.2

**Comment by iTrooz** [comment]
I understand that I can fix the problem myself using the Optimistic approach by doing a try catch over all my requests, but given the purpose of this package is to "simplify using SQLAlchemy with Flask", maybe such a feature could be directly integrated in Flask-SQLAlchemy with the Pessimistic approach ?

**Comment by davidism** [comment]
You pass the relevant option in `SQLALCHEMY_ENGINE_OPTIONS` (or `SQLALCHEMY_BINDS` for other binds). That's the only step. I'm satisfied with the level of simplicity in this regard.

**Comment by iTrooz** [comment]
I added the line `app.config['SQLALCHEMY_ENGINE_OPTIONS'] = {"pool_pre_ping": True}` and it works fine now ! Thanks
