### ISSUE TITLE
Add a way to create a paginated query without executing it

### ISSUE THREAD

**Issue by martinmckenna** [pallets-eco/flask-sqlalchemy#1180]
currently when calling `Query.paginate`, the SQL executes immdiately. This makes the use-case where you want to store the query as a Redis key, so that the result set can be cached and you can return the result set from memory instead of executing the query at all.

Basically what i'm asking for is some kinda functionality like this:

```python
"""
omitting the serialization/deserialization but the gist is something like.....
"""


paginated_query = Query.paginate(page=1, per_page=25, immediate_execution=False)

if(Redis.get(paginated_query)):
   return Redis.get(paginated_query)

result_set = paginated_query.execute()
Redis.set(paginated_query, result_set)
return result_set
```

**Comment by martinmckenna** [comment]
there's obviously ways around this, but it seem like consistent API design that you specifically have to invoke `Query.all()` or `Query.first()` but with pagination, it's an immediate execution.

**Comment by davidism** [comment]
I don't plan to add this. Pagination involves a lot beyond "set limit and offset", the interface intentionally returns an object for working with that. You have the original query, as well as `pagination.page` and `per_page`, if you need to construct the query again.

I suggest looking into SQLAlchemy's docs for information about caching, using query objects as keys is not a typical pattern there. Note that you're passing a query object, not a string, and converting a query object to string wouldn't include parameter values, so using it as a cache key is not a good idea.

**Comment by martinmckenna** [comment]
updated the example code - you're right i was passing the query object, but what i would like to store is the query string as the key and the result set as the value.

i get that i have all the arguments and the original query string, but it's not useful to use `.paginate` if i have to construct the query manually anyway.

pretty much all of the other flask-sqlalchemy APIs provide an easy-to-access query string, except for `paginate` which seems like inconsistent API design
