### ISSUE TITLE
__bind_key__ not working

### ISSUE THREAD

**Issue by Laserlicht** [pallets-eco/flask-sqlalchemy#1189]
Hello,

the bind key is not working for me. Is this a bug, or a problem with my code?

All data is written to `database.db`, but shold be seperated to the two databases. The `database_logging.db` was created but is empty.

The relevant extract of the code. I need the declarative_base because I want to seperate the table definitions over multiple files.

database.py
```
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
```

app.py
```
app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'database/database.db')
app.config['SQLALCHEMY_BINDS'] = {
    'logging': 'sqlite:///' + os.path.join(basedir, 'database/database_logging.db')
}

db = SQLAlchemy(app, model_class=Base)
with app.app_context():
    db.create_all()
```

data.py
```
from sqlalchemy import *
from database.database import Base

class atable(Base):
    __bind_key__ = "logging"
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    abc = Column(Text, nullable=False, index=True)

    def __repr__(self):
        return f'<a {self.abc}>'
    
class btable(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    abc = Column(Text, nullable=False, index=True)

    def __repr__(self):
        return f'<b {self.abc}>'
```

Environment:

- Python version: 3.10
- Flask-SQLAlchemy version: 3.0.3
- SQLAlchemy version: 2.0.9

**Comment by davidism** [comment]
You used your own declarative base instead of ours (ir a subclass), so you don't get the features it provides.

**Comment by Laserlicht** [comment]
Ah `Base = db.Model`... Thanks!
