### ISSUE TITLE
Creates database file in root path as well as instance folder

### ISSUE THREAD

**Issue by ashleycollinge1** [pallets-eco/flask-sqlalchemy#1193]
Multiple sqlite databases being created, one in instance/ folder and one in the root folder.

I'm using the below path for my SQLALCHEMY_DATABASE_URI:

    SQLALCHEMY_DATABASE_URI = sqlite:///database.db

I believe that using this kind of path for the SQLALCHEMY_DATABASE_URI should create the database.db file in the instance/ folder only, but it's creating it there, and in the root path. I'm not sure which it's actually using!

Environment:

- Python version:3.8.10
- Flask-SQLAlchemy version:3.0.3
- SQLAlchemy version:2.0.9

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. The database file is only created in the instance folder.

**Comment by ashleycollinge1** [comment]
Thank you for confirming - was my mistake:

I was using sqlalchemy_utils to create a database which wasn't needed.

    from sqlalchemy_utils import database_exists, create_database
    ...
    if not database_exists(Config.SQLALCHEMY_DATABASE_URI):
        create_database(Config.SQLALCHEMY_DATABASE_URI)

Removed all that and it's doing what it should. Apologies for the time-waste.
