### ISSUE TITLE
Pagination per_page gets wrong value after calling next()

### ISSUE THREAD

**Issue by orlandobcrra** [pallets-eco/flask-sqlalchemy#1201]
When using the `Pagination` and:
- setting the `max_per_page` to a value greater than `100`, 
- setting the `per_page` to a value greater than `100`, 
- after calling `next()`, the `per_page` value gets set to `100` because the `max_per_page` is not carried into the next page.
e.g.
```python
p = Todo.query.paginate(per_page=110, max_per_page=200)
assert len(p.items) == 110 # it works here
p2 = p.next()
assert len(p.items) == 110 # failed, it brings 100 records only.
```

Expected behavior: the next page result set should bring the `per_page` records requested and should not be fixed to `100` records after using the `next()` function.

Environment:

- Python version: 3.7
- Flask-SQLAlchemy version: 3.0.3
- SQLAlchemy version: 1.4.47

**Comment by davidism** [comment]
Happy to review a PR.
