### ISSUE TITLE
Use Flask-SQLAlchemy in celery，A large number of mysql connections were created

### ISSUE THREAD

**Issue by 1456074580** [pallets-eco/flask-sqlalchemy#1204]
Use Flask-SQLAlchemy in celery，My version celery==3.1.25, flache-sqlalchemy ==2.4.4. celery docker configuration: CELERYD_CONCURRENCY = 10, my question is: You Celery Docker configuration: Celeryd_concurrency = 10, my question is: There are a lot of connections created in mysql and don't seem to be Celery pooling?
 My current solution is to configure mysql：
--max_connections=3000
--interactive_timeout=300
--wait_timeout=300
Do you have any good ideas?

**Comment by 1456074580** [comment]
You have a regular task run in celery, which has multiple workers and creates new connections every time you execute it, I do show full PROCESSLIST in mysql, there are a lot of sleep connections and you create new connections every time you execute it.

**Comment by davidism** [comment]
Follow this pattern to ensure that each task is using an app context correctly, which will ensure that Flask-SQLAlchemy returns the connection to the pool when the task is finished: https://flask.palletsprojects.com/patterns/celery/
