### ISSUE TITLE
Little problem with the type hint

### ISSUE THREAD

**Issue by Zoupers** [pallets-eco/flask-sqlalchemy#1205]
![image](https://user-images.githubusercontent.com/29817738/236628413-e7e25309-c173-4d9e-b376-548619a21a4b.png)
sqlalchemy does not exporse orm as a clear attr, so the type hint there is not working.
now we change that to this with full path.
![image](https://user-images.githubusercontent.com/29817738/236628480-11b11690-a200-49c3-94f8-ca3d6a8f83af.png)
And it works out with the type hint.

The main problem with that might be the use of some thing like `db.session`, which I use a lot in project to do CRUD operations. Previously we have that. It will stock since sa don't have orm attr. It's a module.

https://github.com/pallets-eco/flask-sqlalchemy/blob/d137db10e733daf1fd2ad24dd59aedc3072d48e5/src/flask_sqlalchemy/extension.py#L325

And I think we should make this little change to provide more type hint info.

Environment:

- Python version: 3.9.16
- Flask-SQLAlchemy version: 3.0.3
- SQLAlchemy version: 2.0.0 and above

**Comment by davidism** [comment]
It's a bug with pyright: https://github.com/microsoft/pyright/issues/3884. I'm willing to take the suggested fix of `import sqlalchemy.orm as sa_orm`.

**Comment by Zoupers** [comment]
It't not only `sa.orm`, but also `sa.exc` and `sa.event`. But they can adopt the rule to be like `sa_exc` and `sa_event`. OK?

**Comment by davidism** [comment]
Yes, that's what I meant.

**Comment by pamelafox** [comment]
Fixed in 3.0.4 which is now released. Thanks for the PR!
