### ISSUE TITLE
Bug with getting the correct bind when clause is a statement (like Insert)

### ISSUE THREAD

**Issue by ivan-gerov** [pallets-eco/flask-sqlalchemy#1210]
On a Flask app with multiple databases where you have models that have different `__bind_key__` attributes, if you perform a table operation on the model that has its table in a different database `get_bind` cannot find the correct bind key and engine and this raises an OperationError: no such table.

```
@pytest.mark.usefixtures("app_ctx")
def test_session_multiple_dbs(app: Flask) -> None:
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///"
    app.config["SQLALCHEMY_BINDS"] = {"db1": "sqlite:///"}

    db = SQLAlchemy(app)

    class User(db.Model):
        id = sa.Column(sa.Integer, primary_key=True)
        name = sa.Column(sa.String(50), nullable=False)

    class Product(db.Model):
        __bind_key__ = "db1"
        id = sa.Column(sa.Integer, primary_key=True)
        name = sa.Column(sa.String(50), nullable=False)

    db.create_all()

    db.session.execute(User.__table__.insert(), [{"name": "User1"}, {"name": "User2"}])
    db.session.commit()
    users = db.session.execute(db.select(User)).scalars().all()
    assert len(users) == 2

    db.session.execute(
        Product.__table__.insert(), [{"name": "Product1"}, {"name": "Product2"}]
    )
    db.session.commit()
    products = db.session.execute(db.select(Product)).scalars().all()
    assert len(products) == 2

```

In the following test the first insert on User passes, but the second insert on Product fails with the no such table error. This is because the _clause_to_engine function doesn't support cases where clause has a table attribute that holds a bind_key.

Environment:

- Python version: >= 3.8
- Flask-SQLAlchemy version: >=3.0.0
- SQLAlchemy version: >= 1.4.3

**Comment by pamelafox** [comment]
Hi @ivan-gerov, I'm taking a look at this now. I'm new to bind keys so am trying to wrap my head around the bug and the change.

One thing I notice is that the sqlalchemy code doesn't seem to account for the __table__ case, or at least, I only see a check for being an instance of a Table:
https://github.com/sqlalchemy/sqlalchemy/blob/28a66ac2fcee27a938c791fbb62d0220164e42df/lib/sqlalchemy/orm/session.py#L2679

Is this standard SQLAlchemy usage?

db.session.execute(User.__table__.insert(), [{"name": "User1"}, {"name": "User2"}])

I've been looking through the SQLAlchemy docs looking for examples like that and haven't found any yet. It probably is, I just want to make sure for maintainability's sake. Thanks!

**Comment by davidism** [comment]
Seems similar to #1231

**Comment by zedrdave** [comment]
I am having a very similar issue with a slightly more complex use case:

I am defining explicitly `__table__` as a subquery from another table in a declarative model (streamlined version of the real code, but there is a good reason for doing this):

```
class MyModelMeta(type(db.Model)):
    def __new__(mcs, name, bases, attrs):
         ...
         attrs["__bind_key__"] = parent_model.__bind_key__
         attrs["__table__"] = (parent_model.__table__.select()
                .with_only_columns(*selected_columns)
                .subquery(parent_model.__tablename__)
            )
        ....
        return super().__new__(mcs, name, (db.Model,), attrs)

class MyModelView(metaclass=ModelViewMeta):
       ...
```

Both the parent model and this subquery model, use a non-default binding (specified in `__bind_key__`)…

Unfortunately, as of flask-sqlalchemy 3, `__bind_key__` is ignored when `__table__` is present, and any attempt at running `MyModelView.query` or `db.session.execute(MyModelView…` result in a "table not found" error…

Looking through the code, it seems that fsqla is trying to find a bind key by checking if __table__ is a Table (it's not), and reverting to default bind.

Is there any workaround to ensure that a clause-based declarative model can specify a bind key?

**Comment by pamelafox** [comment]
@zedrdave Did you try the patch suggested in https://github.com/pallets-eco/flask-sqlalchemy/pull/1211/ to see if it also resolves your situation?

**Comment by pamelafox** [comment]
Update: I tried the patch on approximation of @zedrdave's code and it does not resolve it.

**Comment by pamelafox** [comment]
Just reporting on more digging into that code - it looks like that general approach is what's documented here (though with 2.0 style class): https://docs.sqlalchemy.org/en/20/orm/nonstandard_mappings.html#mapping-a-class-against-arbitrary-subqueries
It contains a note discouraging its use: "The practice of mapping to arbitrary SELECT statements, especially complex ones as above, is almost never needed; it necessarily tends to produce complex queries which are often less efficient than that which would be produced by direct query construction. The practice is to some degree based on the very early history of SQLAlchemy where the [Mapper](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.Mapper) construct was meant to represent the primary querying interface; in modern usage, the [Query](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query) object can be used to construct virtually any SELECT statement, including complex composites, and should be favored over the “map-to-selectable” approach."

**Comment by pamelafox** [comment]
This is the code I've been working with to dig into that issue:

```
db = SQLAlchemy(app)

class User(db.Model):
    __bind_key__ = "db1"
    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)

class MyModelMeta(type(db.Model)):
    def __new__(mcs, name, bases, attrs):
        attrs["__bind_key__"] = User.__bind_key__
        attrs["__table__"] = (
            User.__table__.select()
            .subquery(User.__tablename__)
        )
        return super().__new__(mcs, name, (db.Model,), attrs)

class MyModelView(metaclass=MyModelMeta):
    pass

with app.app_context():
    db.drop_all()
    db.create_all()
    result = db.session.execute(db.select(MyModelView))
```

With that code, our extension receives an instance of `sqlalchemy.sql.selectable.Subquery`. I've dug into that object extensively and have not found a way to get at the original model class, so that we can get the bind key. This might be resolvable, but currently, I think we defer subquery support, especially given the docs suggest its more of a legacy thing.

**Comment by pamelafox** [comment]
Just following up on my earlier comment about not finding code like the original report from @ivan-gerov, I did end up finding some similar test cases like:

https://github.com/sqlalchemy/sqlalchemy/blob/8503dc2e948908199cd8ba4e6b1d1ddcf92f4020/examples/performance/large_resultsets.py#L50

s.execute(Customer.__table__.insert(), ..)

So it does seem useful to support, and insert/update statements are straightforward, as they always have an associated table.

**Comment by pamelafox** [comment]
@zedrdave Please file yours as a separate issue if you are still hopeful there's a way for this extension to support it, and if the Query approach doesnt work for you. 

The originally reported issue is now fixed. Thanks @ivan-gerov for the PR!
