### ISSUE TITLE
When I add ModelMixin, db.Model loses the typing prompt

### ISSUE THREAD

**Issue by six1203** [pallets-eco/flask-sqlalchemy#1240]
Environment:

- Python version: 3.8.15
- Flask-SQLAlchemy version: 3.0.0
- SQLAlchemy version: 1.4.42

**Comment by six1203** [comment]
class db(SQLAlchemy):
  
    def init_app(self, app: Flask) -> None:
        if app.config["TESTING"]:
            dsn_list = [app.config["SQLALCHEMY_DATABASE_URI"]]
            if app.config.get("SQLALCHEMY_BINDS") is not None:
                dsn_list.extend(
                    [x["url"] for x in app.config["SQLALCHEMY_BINDS"].values()]
                )
            for dsn in dsn_list:
                if not database_exists(dsn):
                    create_database(dsn)

        super().init_app(app)
        
class ModelMixin(object):
    def as_dict(self) -> Dict[str, Any]:
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

class CustomerPurchaseRedemption(db.Model, ModelMixin):
    __tablename__ = "customer_purchase_redemption"

    id = db.Column(db.BigInteger, primary_key=True)
    customer_name = db.Column(
        db.String(255, "utf8mb4_unicode_ci"),
        nullable=False,
        server_default=db.FetchedValue(),
        info="客户名称",
    )

**Comment by six1203** [comment]
![image](https://github.com/pallets-eco/flask-sqlalchemy/assets/35206994/5e6adf47-a1e5-4adc-91d4-3115e17e7a69)
loses the typing prompt

**Comment by davidism** [comment]
I'm fairly sure that's outside our control. But if you discover otherwise, I'm happy to review a PR.
