### ISSUE TITLE
Issue in the ORM caused by Flask-SQLAlchemy

### ISSUE THREAD

**Issue by ibraheemalayan** [pallets-eco/flask-sqlalchemy#1267]
Environment:

- Python version: 3.9.16
- Flask-SQLAlchemy version: 3.1.1
- SQLAlchemy version: 2.0.21

The issue was explained in a discussion thread in the SqlAlchemy repository, but when using normal `SqlAlchemy` instead of  `Flask-SQLAlchemy` the issue disappears, indicating it has something to do with this package.

[Link of the discussion](https://github.com/sqlalchemy/sqlalchemy/discussions/10461)

**Comment by davidism** [comment]
When reporting an issue, please include a complete description along with a minimal reproducible example in the issue itself, not as links to elsewhere. Please open a new issue with the necessary format.

**Comment by ibraheemalayan** [comment]
@davidism I thought it would be better to discuss the topic on the SQLAlchemy thread since the issue might be in SQLAlchemy not here, and the SQLAlchemy team there can help us investigate it more. 
Anyway as you want I am opening a new issue.
