### ISSUE TITLE
Add documentation related to commit on teardown

### ISSUE THREAD

**Issue by mrexodia** [pallets-eco/flask-sqlalchemy#1271]
I found the discussion about `SQLALCHEMY_COMMIT_ON_TEARDOWN` in #216, but found things a bit confusing. It seems to me like this feature was removed because of a historical bug in Flask and the following code should correctly work in 2023:

```python
from sqlalchemy.exc import SQLAlchemyError

@app.errorhandler(SQLAlchemyError)
def handle_db_exceptions(error):
    print(f"SQLAlchemy error: {error}")
    db.session.rollback()

@app.teardown_appcontext
def teardown(exception):
    try:
        db.session.commit()
    except Exception as e:
        print(f"Exception during teardown: {e}")
```

The proposal would be to add a snippet like this to the documentation (perhaps also with a `@app.teardown_request` to automatically commit at the end of a request). I understand there are philosophical objections to automatically committing, but why not leave that for the user to decide? I think in certain cases it's better to commit per default and let the user handle rollbacks depending on their business logic. Currently the documentation implies that there is no correct way to do this and handwaves about 'design issues' that are no longer relevant(?)

**Comment by davidism** [comment]
Commit on teardown is not a pattern we want to promote. You should commit explicitly, directly after the operation you want to commit. The session is already removed after the request, which will already rollback any remaining uncommitted operations. The entire pattern is not needed.
