### ISSUE TITLE
Proposal : Make pagination query pameters parametrized

### ISSUE THREAD

**Issue by gdoumenc** [pallets-eco/flask-sqlalchemy#1288]
Flask-SQLAlchemy uses `page`, `per_page` for pagination.

The proposal is to make those parameters defined in configuration allowing then to use Flask-SQLAlchemy to be comptabile with JSON:API parameters ; `page[number]` and `page[size]`

This could be defined as :
```
    app.config.setdefault("SQLALCHEMY_PAGE_QUERY_PARAM", "page")
    app.config.setdefault("SQLALCHEMY_PER_PAGE_QUERY_PARAM", "per_page")
```
and used as :

```
    page_query_param = current_app.config["SQLALCHEMY_PAGE_QUERY_PARAM"]
    page = int(request.args.get(page_query_param, 1))
```

**Comment by davidism** [comment]
If you need custom behavior here, you can write a wrapper function that takes the query and passes the appropriate arguments to the paginate method. That allows customizing the source more than the proposed configuration could.
