### ISSUE TITLE
Model relationships show typing error when used with `Mapped` type

### ISSUE THREAD

**Issue by bdewilde** [pallets-eco/flask-sqlalchemy#1291]
Recently I've been updating my `sqlalchemy` v1.4-style declarative models to the newer v2.0, which allows for static analysis of types in my editor. This has worked great for columns  -- `x = db.Column(...)` => `x: Mapped[TYPE] = mapped_column(...)` -- but doing the equivalent for model relationships shows an error in my editor:

```
Expression of type "RelationshipProperty[Any]" cannot be assigned to declared type "Mapped[TYPE]"
  "RelationshipProperty[Any]" is incompatible with "Mapped[TYPE]"
```

This error message does not appear if I replace `db.relationship()` with `sqlalchemy.orm.relationship()` and leave everything else as-is.

Adapt the first simple relationship example from [the sqlalchemy docs](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#declarative-vs-imperative-forms) --

```python
class Parent(db.Model):
    __tablename__ = "parent_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    children: Mapped[List["Child"]] = db.relationship(back_populates="parent")


class Child(db.Model):
    __tablename__ = "child_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    parent_id: Mapped[int] = mapped_column(ForeignKey("parent_table.id"))
    parent: Mapped["Parent"] = db.relationship(back_populates="children")
```

In my editor, this shows error messages for both relationship attributes, along the lines of `Expression of type "RelationshipProperty[Any]" cannot be assigned to declared type "Mapped[list[Child]]"
  "RelationshipProperty[Any]" is incompatible with "Mapped[list[Child]]"`

I would expect that no error messages would be visible, and that static analysis would understand that the type and assigned value are consistent.

Environment:

- Python version: 3.10
- Flask-SQLAlchemy version: 3.1.1
- SQLAlchemy version: 2.0.23

**Comment by davidism** [comment]
You'll need to report that to SQLAlchemy, this extension doesn't deal with this typing information.

**Comment by bdewilde** [comment]
Hi @davidism , I'm not sure I follow your reasoning -- using `sqlalchemy` directly works fine, it's the `flask-sqlalchemy` interface to that underlying functionality that doesn't behave as expected. This isn't a blocking problem, I can just use `sqlalchemy.orm.relationship()` instead of `db.relationship()`. But it's not ideal to diverge from this package's documented interface.
