### ISSUE TITLE
ImportError: cannot import name '_QueryProperty' from 'flask_sqlalchemy'

### ISSUE THREAD

**Issue by fatjan** [pallets-eco/flask-sqlalchemy#1307]
I am using Flask-SQLAlchemy version 3.1.1
and I have the following import error issue:

`ImportError: cannot import name '_QueryProperty' from 'flask_sqlalchemy'`

`File "/Users/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/flask_appbuilder/models/sqla/__init__.py", line 5, in <module>`

![Screenshot 2024-01-30 at 12 17 52](https://github.com/pallets-eco/flask-sqlalchemy/assets/46950501/808b35ce-90d8-466b-a0cb-128b298fd08f)

Replicate:
use Flask-SQLAlchemy version 3.1.1 in a Flask app

Expected behaviour:
the `_QueryProperty` should be successfully imported from `flask_sqlalchemy` without any issue

Environment:

- Python version: 3.9.16
- Flask-SQLAlchemy version: 3.1.1
- SQLAlchemy version: 2.0.23

**Comment by davidism** [comment]
That's no longer available, as the internal API has changed in version 3. Be sure to check changelogs, deprecation warnings, and what's marked as not public.

**Comment by davidism** [comment]
That's no longer available, as the internal API has changed significantly in version 3. It was not marked as part of the public API. Note that the `query` API is considered legacy in SQLAlchemy 2, and you should migrate to its new execution API when possible. SQLAlchemy also provides it directly: https://docs.sqlalchemy.org/en/20/orm/contextual.html#sqlalchemy.orm.scoped_session.query_property
