### ISSUE TITLE
query.filter_by not returning correct type of record - is this a bug?

### ISSUE THREAD

**Issue by scath999** [pallets-eco/flask-sqlalchemy#1358]
### Discussed in https://github.com/pallets-eco/flask-sqlalchemy/discussions/1354

<div type='discussions-op-text'>

<sup>Originally posted by **scath999** June 30, 2024</sup>
I have a child model than inherits from a parent.

I want to access a relationship that exists on the child (in this example, "extras"), which is not on the parent.

When I query and find the child, the ORM returns the object as the parent type, making it impossible for me to access the relationship.

This is not happening when I use the terminal.

I'm unsure if this is an issue with my code, flask_sqlalchemy, or sqlalchemy. Guidance is welcome.

Example

```
class Parent (db.Model):   
    id              = db.Column(db.Integer, primary_key=True, unique=True,)
    first_name      = db.Column(db.String(20))
    last_name       = db.Column(db.String(20))


class Child (Parent):
    __tablename__ = "child"
    __mapper_args__ = {"polymorphic_identity": "child"}

    id          = db.Column(db.Integer, db.ForeignKey("Parent.id"), primary_key=True)
    extras      = db.relationship('Extra', backref='Child', lazy=True)


class Extra(db.Model):
    id           = db.Column(db.Integer, unique=True, primary_key=True)
    child_id     = db.Column(db.Integer, db.ForeignKey("Child.id"), nullable=False)
    text_of_extra = db.Column(db.String, nullable=False)    
```

A simplified extract of my code looks roughly like:

```
the_child = Child.query.filter_by(id=child_id).first() # Simplified query demonstrating the point

print(f"child[ {the_child.id} ] has extras: {the_child.extras}")
```

The result is puzzling:
``` AttributeError: 'Parent' object has no attribute 'extras' ```

**Note** that the object reported is _'Parent'_ despite the query being made explicitly on _'Child'_.

**However,** from the CLI

```
>>> with app.app_context():
 ...                 the_child = Child.query.filter_by(id=child_id).first()
 ...
 >>> the_child
<Child 001>               
>>> the_child.extras
<sqlalchemy.orm.dynamic.AppenderQuery object at 0x000002649705F460>
```

**Comment by scath999** [comment]
@davidism Can you help me understand your rationale for closing this without comment?

**Comment by ThiefMaster** [comment]
My guess would be the lack of a self-contained snippet to reproduce this. Especially for more obscure issues like this one, it's good to have a small file that can be simply executed via `python whatever.py` to demonstrate the problem.

And preparing this also ensures that it's not something else in your code doing it.

**Comment by davidism** [comment]
Also it's a question about your own code, and you already have an open post about it.

**Comment by scath999** [comment]
Ok. I initially opened this as a discussion question and left it up for four days; no-one seemed interested in answering.

I then converted it to a ticket to create more visibility - which worked, you saw it - only to have you silently close it.

I understand this isn't your day job - the project this pertains to for me isn't mine either - but you don't have 100+ open tickets that you need to triage. 

If you're just too busy, perhaps getting some volunteers to peek in on the discussion area and point people in the right direction would be helpful?

Thanks for your time, I guess.

**Comment by ThiefMaster** [comment]
If you add a snippet to reproduce it that confirms it's a problem on our side, we'll gladly reopen this. :)

Please note that this is also more scalable: If everyone posts a non-executable example of something that doesn't work, then it's O(n) on our side to turn it into something we can actually test, see if it we can reproduce the issue, etc.

OTOH, if everyone does that before reporting a problem, then it means that:

- It's (usually) already clear that it's NOT a problem with your code or something weird you're doing there (we don't know your code besides what you posted)
- We can now immediately take that snippet, run it, and most likely figure out what's wrong - in less time that it'd have taken us to create the snippet to reproduce it.

**Comment by scath999** [comment]
@ThiefMaster I hear ya, and I've been there; I can see your side. I was trying to save everyone some trouble. 

Ideally, something like "Hey, we're not sure where this is going wrong - create a full ticket and we'll take a look" or "We've seen that before, it's an upstream issue. Create a ticket with that project" would have been the response to my discussion question. You've sort-of done that here, so I'll post a full code snippet when I have a chance. 

Thanks again.
