### ISSUE TITLE
Enable sharing of fields/methods between model classes

### ISSUE THREAD

**Issue by yang** [pallets-eco/flask-sqlalchemy#157]
E.g., I want ID, created, etc. available for all my model classes (and with values automatically generated in `__init__`).  However, simply subclassing the base model class and then subclassing from that doesn't work.

**Comment by mehdibaghdadi** [comment]
just add **AbstractConcreteBase** to your base class

`
from sqlalchemy.ext.declarative import declarative_base , AbstractConcreteBase

class BaseModel(AbstractConcreteBase, object):
    id = Column(Integer, primary_key=True, index=True)

   def say_hello(self):
      print("Model {id} says hello".format(id=self.id))

   @classmethod
    def cls_method(cls):`
