### ISSUE TITLE
Memory leak in DEBUG mode

### ISSUE THREAD

**Issue by iurisilvio** [pallets-eco/flask-sqlalchemy#181]
Flask-SQLAlchemy record all SQL queries in debug mode. I agree it is useful to debug but it also consume all my memory in long running processes. E.g. a celery task importing a lot of data to my database.

I suggest a hard limit to record only last N queries.

Also, if I just set `SQLALCHEMY_RECORD_QUERIES=False`, it is ignored because it always record in debug mode.

**Comment by jeffwidman** [comment]
> But I'll make sure it's in for 3.0.

Shouldn't it be re-opened then and added to the 3.0 milestone?

**Comment by jpsyri** [comment]
Given that it's been 4 years and we are still not in the version 3, would it be possible to consider some workaround for this in the version 2? Disabling debug globally every time you want to test larger batch job gets quite annoying after a while. (Also disabling global debug also disables everything else that might be useful in the testing, not just query recording)
