### ISSUE TITLE
Getting this error daily: "SQLError: (OperationalError) (2006, ‘MySQL server has gone away’)"

### ISSUE THREAD

**Issue by aaront** [pallets-eco/flask-sqlalchemy#2]
It only happens, as the article says, if the server has been inactive for about 8 hours. Since my site is part of an office intranet, this happens daily.

Wondering how to go about fixing this with Flask-SQLAlchemy.

More info here: http://rapd.wordpress.com/2008/03/02/sqlalchemy-sqlerror-operationalerror-2006-mysql-server-has-gone-away/

**Comment by linzhi** [comment]
got the same error....

**Comment by louking** [comment]
@linzhi did you check the MySQL interactive_timeout on your hosting server? SQLALCHEMY_POOL_RECYCLE needs to be set less than that value.

**Comment by zky001** [comment]
need determine the stutas
