### ISSUE TITLE
Flask-SQLAlchemy does not create __tablename__ for classes that inherit an ID

### ISSUE THREAD

**Issue by abendebury** [pallets-eco/flask-sqlalchemy#205]
If I have the following models:

```
class IDMixin(object):
    id = db.Column(db.Integer, primary_key=True)

class Model(db.Model, IDMixin):
    field = db.Column(db.String)
```

I will get an error like this:

```
sqlalchemy.exc.InvalidRequestError: Class <class 'app.models.Project'> does not have a __table__ or __tablename__ specified and does not inherit from an existing table-mapped class.
```

The problem is that there is no ID defined on Model: even though it inherits from IDMixin, SQLAlchemy does not recognize that attribute and setting **tablename** through db.Model is unsuccessful.

It should be possible to have the above code work.

**Comment by davidism** [comment]
This is addressed by #248.
