### ISSUE TITLE
How can I get the version in latest version of Flask-SqlAlchemy?

### ISSUE THREAD

**Issue by chfw** [pallets-eco/flask-sqlalchemy#207]
Hi all,

I am using Flask-SQLAlchemy==1.0 but it has bugs in **init.py** line 175:

```
@staticmethod
def session_signal_after_rollback(session):
    session._model_changes.clear() <--- bug, do not check if it's none or not
```

However, the latest code in github contains far better code. How can I get this development version through pip install?

Thanks,

chfw

**Comment by n-bhasin** [comment]
hi, i installed flask-sqlalchemy completely.
but when i import into my app.py file i get error NoModuleFound error.

my  code goes like this..
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.secret_key = "my precious"
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///contact.db'

db = SQLAlchemy(app)


@app.route('/')
def index():
	return "Ok"


if __name__ == '__main__':
	app.run(debug=True)


anyone just help me with this
