### ISSUE TITLE
Fail to create an object

### ISSUE THREAD

**Issue by jxWho** [pallets-eco/flask-sqlalchemy#211]
When I was trying to create an object, I got this error:

UnmappedClassError: Class 'sqlalchemy.sql.sqltypes.Integer' is not mapped

What should I do to fix it?

Thank you!

**Comment by sinanm89** [comment]
saved me a ton of time guys thanks!

**Comment by ngeorgj** [comment]
@lorey solved my problem,

i was using db.relationship in both models.

thanks mate!
