### ISSUE TITLE
Quickstart presents a potential circular import pattern

### ISSUE THREAD

**Issue by ionrock** [pallets-eco/flask-sqlalchemy#230]
I might be missing something here, so please feel free to correct me where I'm getting this wrong. The quick start example (and other subsequent examples) use the app as the base for models. 

```
# models.py
from app import db
class MyModel(db.Base):
    ...
```

In app you configure the database by adding the connection string to the config. This makes sense so far. 

But if you have a handler in your app.py, how can you import your model?

```
# in app.py
from app.models import MyModel  # A circular import as models imports db from app.py
```

Obviously others have solved this problem, but the documentation doesn't really provide a clear example of how to configure the database to use the db created from the flask app.

I'd assume the recommended solution would be to have an `app.py`, `handlers.py` and `models.py` where the handlers import the app object from app.py and models from `models.py` and `models.py` imports the app from `app.py`. 

Please let me know if I'm totally off base here. I'm just starting with flask and when going from the examples to an actual app, the above step was not obivious (assuming that is the recommended pattern).

Thanks!

**Comment by jeremywhittington** [comment]
This is a dead link, what was the answer?

**Comment by zealseeker** [comment]
> This is a dead link, what was the answer?

http://flask.pocoo.org/docs/1.0/patterns/packages/
