### ISSUE TITLE
A commit_on_success decorator

### ISSUE THREAD

**Issue by yashh** [pallets-eco/flask-sqlalchemy#4]
Since most of the projects using sqlalchemy uses mysql / postgres there is a good chance of using transactions. Having a commit_on_success decorator can save a try except block in the view functions. Here is a rough draft of the decorator I wrote. 

https://gist.github.com/14d12595f3dfa307a354

Just wondering if its a good idea to get the db object from the function object. (line # 11)?

**Comment by daym** [comment]
@mitsuhiko: Where does the rollback happen?

**Comment by ThiefMaster** [comment]
https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L852 most likely causes a rollback somewhere inside SQLAlchemy
