### ISSUE TITLE
get_bind does not check the instance of its "mapper" attribute

### ISSUE THREAD

**Issue by nikoskaragiannakis** [pallets-eco/flask-sqlalchemy#590]
I've been using sqlalchemy in the past and recently I've been experimenting with flask-sqlalchemy (using sqlalchemy's declarative system for my models).

When I make a raw sql query, I have to get the mapper for my declarative class (let's call it `MyModel` in the example) via `inspect` function in order to get a binding 
```python
        response = session.execute(my_raw_sql_query,
                                   ...,
                                   bind=session.get_bind(inspect(MyModel)))
```
because `get_bind` in flask-sqlalchemy expects a Mapper object https://github.com/mitsuhiko/flask-sqlalchemy/blob/f465142ea1643b4f0fe50540780ef9a6bf2c7e53/flask_sqlalchemy/__init__.py#L157

However, I didn't need to do that with base method [sqlalchemy.orm.session.get_bind](https://github.com/zzzeek/sqlalchemy/blob/699272e4dcb9aa71ebbc0d9487fb6de82d3abc2b/lib/sqlalchemy/orm/session.py#L1356) which does the inspection.

My question is why doesn't the flask-sqlalchemy's `get_bind` follow the flexibility of the base method?

**Comment by davidism** [comment]
Should be fixed in #1087. However, the example code shown doesn't make a lot of sense, Flask-SQLAlchemy's session already handles choosing the bind for a given model or table.
