### ISSUE TITLE
Support __iter__ on Pagination instances.

### ISSUE THREAD

**Issue by rduplain** [pallets-eco/flask-sqlalchemy#70]
I never remember to call .items, and I was just reminded of this when getting a new developer spun up.  Instead of:

```
for obj in MyModel.query.paginate(1).items: pass
```

I expect:

```
for obj in MyModel.query.paginate(1): pass
```

... because SQLAlchemy's query API does this everywhere.  This fails, because a Pagination instance is not iterable.

**Comment by davidism** [comment]
fixed in #1087
