### ISSUE TITLE
Documention about raw connections with multiples databases

### ISSUE THREAD

**Issue by rafaelreuber** [pallets-eco/flask-sqlalchemy#768]
flask-sqlalchemy support multiple connections through binds, but the documentation how to use raw connections is missing. 

The issue [#107](https://github.com/pallets/flask-sqlalchemy/issues/107) shows you could get the bind connection engine just using `db.get_engine(app, 'oh_my_bind').execute(...)`.

The is missing the documentation about this nice feature.

**Comment by kennysong** [comment]
Apparently `engine.execute()` is [deprecated in SQLAlchemy 2.0](https://docs.sqlalchemy.org/en/14/core/connections.html#connectionless-execution-implicit-execution).

I think the future-proof way to do this will be something like `db.create_scoped_session(...).execute(...)`.

**Comment by davidism** [comment]
Yes, `engine.execute` is deprecated in SQLAlchemy itself. You don't need to create a session (and can't after #1087 makes those setup methods private), you should just do `db.session.execute`. #1087 makes the engines available in the `db.engines` dict mapping bind keys to engines.
