### ISSUE TITLE
Possible issue during getting engine for bind with python in optimized mode (PYTHONOPTIMIZE=1)

### ISSUE THREAD

**Issue by krasoffski** [pallets-eco/flask-sqlalchemy#808]
flask-sqlalchemy returns meaningless error when trying to get engine for bind when configuration does not contain any binds for python in optimized mode **(assertions is not evaluated)**.
```
  File "replica.py", line 66, in replica_session
    engine = self._db.get_engine(bind='replica')
  File "/app/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/app/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 549, in get_engine
    uri = self.get_uri()
  File "/app/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 545, in get_uri
    return binds[self._bind]
TypeError: tuple indices must be integers or slices, not str
```
Quick investigation showed that default value when no binds found is `tuple` but on the last line expected a `dict`: [`source code`](https://github.com/pallets/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L545,L549)

**Expected behavior is following:**
Remove assertion and use specific error for this or keep assertion but replace default value with empty `dict` like: `binds = self._app.config.get('SQLALCHEMY_BINDS') or {}` because [documentation](https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/) shows that this value should be a `dict`:
```
SQLALCHEMY_BINDS = {
    'users':        'mysqldb://localhost/users',
    'appmeta':      'sqlite:////path/to/appmeta.db'
}
```

**Comment by Jukka-Sarasti** [comment]
I encountered this issue when reading the configuration variable 'SQLALCHEMY_BINDS' from an .env file. The variable was parsed as a string type and not as a dict. When importing configuration variables as a class using:
`app.config.from_object(Config)` 

I modified the Config class with:

`class Config(object):`
`import ast`
`SQLALCHEMY_BINDS=ast.literal_eval(os.environ.get('SQLALCHEMY_BINDS'))`

**Comment by davidism** [comment]
#1087 no longer uses assert for this.
